apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: ClusterIP
  selector:
    - open.shock.toys/service: api
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  internalTrafficPolicy: Local