apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshock.fullname" . }}-db-service
spec:
  type: ClusterIP
  selector:
    open.shock.toys/service: postgres
  ports:
    - name: "psql"
      port: 5432
      targetPort: 5432