apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshock.fullname" . }}-frontend
  labels:
    open.shock.toys/service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      open.shock.toys/service: frontend
  template:
    metadata:
      labels:
        open.shock.toys/service: frontend
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: PUBLIC_SITE_URL
            value: {{ .Values.links.frontend.baseUrl }}
          - name: PUBLIC_SITE_SHORT_URL
            value: {{ .Values.links.frontend.shortUrl }}
          - name: PUBLIC_BACKEND_API_URL
            value: {{ .Values.links.api.baseUrl }}
          - name: PUBLIC_GATEWAY_CSP_WILDCARD
            value: {{ .Values.links.frontend.cspWildcard }}
          - name: PUBLIC_SITE_NAME
            value: {{ .Values.frontend.siteName }}
          image: ghcr.io/openshock/frontend:latest
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
