apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openshock.prefix.frontendMiddleware" . }}-osr-c
spec:
  redirectRegex:
    regex:  ^{{ .Values.links.frontend.shortUrl }}/c/(.*)
    replacement: {{ .Values.links.frontend.baseUrl }}/#/public/proxy/shares/code/$1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openshock.prefix.frontendMiddleware" . }}-osr-s
spec:
  redirectRegex:
    regex:  ^{{ .Values.links.frontend.shortUrl }}/s/(.*)
    replacement: {{ .Values.links.frontend.baseUrl }}/#/public/proxy/shares/links/$1
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openshock.prefix.frontendMiddleware" . }}-osr-t
spec:
  redirectRegex:
    regex:  ^{{ .Values.links.frontend.shortUrl }}/t/(.*)
    replacement: {{ .Values.links.frontend.baseUrl }}/#/public/proxy/token/$1
---