apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshock.fullname" . }}-frontend
  labels:
    open.shock.toys/service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      open.shock.toys/service: frontend
  template:
    metadata:
      labels:
        open.shock.toys/service: frontend
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: OPENSHOCK_API_URL
            value: {{ .Values.links.api.baseUrl }}
          - name: OPENSHOCK_NAME
            value: {{ .Values.frontend.siteName }}
          - name: OPENSHOCK_SHARE_URL
            value: {{ .Values.links.frontend.shortUrl }}
          - name: OPENSHOCK_URL
            value: {{ .Values.links.frontend.domain }}
          image: ghcr.io/openshock/webui:latest
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
