apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openshock.fullname" . }}-frontend-ingress
    {{- with .Values.frontend.ingress.annotations }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "openshock.fullname" . }}-frontend-middleware-osr-c {{ include "openshock.fullname" . }}-frontend-middleware-osr-l {{ include "openshock.fullname" . }}-frontend-middleware-osr-t
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.frontend.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openshock.fullname" $ }}-frontend-service
                port:
                  number: 80
    {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}