apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshock.fullname" . }}-gateway-service
spec:
  type: ClusterIP
  selector:
    open.shock.toys/service: gateway
  ports:
    - name: "http"
      port: 80
      targetPort: 80