apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshock.fullname" . }}-redis-service
spec:
  type: ClusterIP
  selector:
    open.shock.toys/service: redis
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379