apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshock.fullname" . }}-redis-deployment
  labels:
    open.shock.toys/service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      open.shock.toys/service: redis
  template:
    metadata:
      labels:
        open.shock.toys/service: redis
    spec:
      containers:
      - name: redis
        env:
          - name: REDIS_ARGS
            value: --notify-keyspace-events KEA
        image: redis/redis-stack-server:latest
        ports:
        - containerPort: 5432
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - redis-cli ping | grep PONG
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 3
        volumeMounts:
          - mountPath: /data
            name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data