apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deployment
  labels:
    open.shock.toys/service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      open.shock.toys/service: postgres
  template:
    metadata:
      labels:
        open.shock.toys/service: postgres
    spec:
      containers:
      - name: db
        env:
        - name: POSTGRES_DB
          value: {{ .Values.db.database }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.password }}
        - name: POSTGRES_USER
          value: {{ .Values.db.username }}
        image: {{ .Values.db.image }}
        ports:
        - containerPort: 5432
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data