replicaCount: 1

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

db:
  image: postgres:16
  database: openshock
  username: openshock
  password: changeme

links:
  frontend:
    domain: openshock.local
    baseUrl: https://openshock.local
    cookieDomain: openshock.local
    shortUrl: https://openshock.local
  api:
    baseUrl: https://api.openshock.local

api:
  turnstile:
    # Cloudflare turnstile
    enable: false
    siteKey: ""
    secretKey: ""
  ingress:
    annotations: []
    className: traefik
    hosts:
      - api.openshock.local
    # tls: []
    tls:
      - secretName: api-ingress-secret
        hosts:
          - api.openshock.local
  mail:
    sender:
      name: OpenShock System
      email: system@openshock.app
    #type: MAILJET
    type: SMTP
    #mailjet:
    #  key: mailjetkey
    #  secret: mailjetsecret
    #  template:
    #    passwordReset: 9999999
    smtp:
      host: mail.domain.zap
      port: 587
      username: open@shock.zap
      password: password
      ssl:
        enabled: true
        verifyCert: true

frontend:
  siteName: OpenShock
  ingress:
    annotations: []
    className: traefik
    hosts:
      - openshock.local
    # tls: []
    tls:
      - secretName: frontend-ingress-secret
        hosts:
          - openshock.local

gateway:
  countryCode: DE
  fqdn: gateway.openshock.local
  redis:
    host: redis
  ingress:
    annotations: []
    className: traefik
    hosts:
      - gateway.openshock.local
    # tls: []
    tls:
      - secretName: gateway-ingress-secret
        hosts:
          - gateway.openshock.local